### ISSUE TITLE
Hide the "File encrypted" green feedback text when a file is dropped in the dropzone

### ISSUE THREAD

**Issue by vortice3D** [meixler/web-browser-based-file-encryption-decryption#2]
Hi there, @meixler:

First, congratulations for this code, I use it to encrypt GLBs and really appreciate it.

Said this, a UX-related aspect I think may be improved (in a really easy way) is to hide the "File encrypted" green feedback text when a file is dropped in the dropzone. one you encryp a file It's always sitted there, being so a bit annoying when you're encrypting/devrypting several files with the same password.

Best regards.

**Comment by meixler** [comment]
@vortice3D Thanks for your feedback, and I'm glad that you found this project useful.  There are actually a number of things that change in the UI and internally in the state of the page after you encrypt a file.  So, the simplest way to return the page to its initial state after encrypting a file and saving the encrypted file to your system is to use the 'refresh page' button in the upper right-hand corner of the page.
